include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    use_setters_to_change_properties: false
    avoid_classes_with_only_static_members: false
    always_use_package_imports: false
    flutter_style_todos: false
    prefer_relative_imports: true
    unnecessary_parenthesis: false
    one_member_abstracts: false
    no_leading_underscores_for_local_identifiers: false

errors:
  invalid_annotation_target: ignore
  invalid_use_of_protected_member: error
  prefer_const_constructors: warning
  curly_braces_in_flow_control_structures: error
  unused_import: error
  sdk_version_since: ignore

  analyzer:
    exclude:
      - "**/*.g.dart"
      - "**/*.freezed.dart"