name: meli_search
description: Search meli products with their details
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.6.1

dependencies:
  bloc: 9.0.0
  cached_network_image: 3.4.1
  equatable: 2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: 9.0.0
  flutter_localizations:
    sdk: flutter
  injector: 4.0.0
  intl: 0.19.0
  json_annotation: 4.9.0
  logger: 2.5.0
  retrofit: 4.4.2

dev_dependencies:
  bloc_test: 10.0.0
  build_runner: 2.4.14
  flutter_test:
    sdk: flutter
  json_serializable: 6.9.3
  mocktail: 1.0.4
  retrofit_generator: 9.1.7
  very_good_analysis: 7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proximanova-light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/proximanova-regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/proximanova-semibold.ttf
          weight: 600
          style: normal